package mcservice

// ConfigSchemaRegistry stores predefined settings with rich Korean descriptions.
var ConfigSchemaRegistry = []SettingSchema{
	// ==========================================
	// 1. server.properties 전수 항목 (Standard Server Properties)
	// ==========================================
	// [기본 설정]
	{
		Source:      "properties",
		Key:         "difficulty",
		Type:        TypeSelect,
		LabelKR:     "게임 난이도",
		Description: "서버의 전반적인 난이도를 설정합니다.",
		Category:    "기본 설정",
		Options:     []string{"peaceful", "easy", "normal", "hard"},
	},
	{
		Source:      "properties",
		Key:         "gamemode",
		Type:        TypeSelect,
		LabelKR:     "기본 게임 모드",
		Description: "신규 접속 플레이어에게 기본 부여되는 게임 모드입니다.",
		Category:    "기본 설정",
		Options:     []string{"survival", "creative", "adventure", "spectator"},
	},
	{
		Source:      "properties",
		Key:         "force-gamemode",
		Type:        TypeBool,
		LabelKR:     "게임 모드 강제 적용",
		Description: "플레이어가 재접속할 때 이전 모드를 무시하고 기본 게임 모드로 강제 설정합니다.",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "hardcore",
		Type:        TypeBool,
		LabelKR:     "하드코어 모드",
		Description: "플레이어 사망 시 부활하지 못하고 영구 관전(Spectator) 모드로 전환됩니다.",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "motd",
		Type:        TypeString,
		LabelKR:     "서버 목록 환영 문구 (MOTD)",
		Description: "마인크래프트 서버 목록 화면에 표시되는 환영 및 설명 문구입니다.",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "server-name",
		Type:        TypeString,
		LabelKR:     "서버 이름",
		Description: "서버 목록 및 상태 쿼리에 노출되는 서버 고유 명칭입니다.",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "server-port",
		Type:        TypeNumber,
		LabelKR:     "서버 포트",
		Description: "마인크래프트 게임 클라이언트가 접속하는 주 포트입니다. (기본: 25565)",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "server-ip",
		Type:        TypeString,
		LabelKR:     "서버 바인딩 IP",
		Description: "서버를 특정 네트워크 인터페이스 IP에 바인딩합니다. (비워두면 모든 IP에 바인딩)",
		Category:    "기본 설정",
	},
	{
		Source:      "properties",
		Key:         "max-players",
		Type:        TypeNumber,
		LabelKR:     "최대 접속자 수",
		Description: "동시에 접속할 수 있는 최대 플레이어 수입니다.",
		Category:    "기본 설정",
	},

	// [게임플레이 & 규칙]
	{
		Source:      "properties",
		Key:         "pvp",
		Type:        TypeBool,
		LabelKR:     "PVP (플레이어 전투)",
		Description: "플레이어 간 공격 및 데미지 전달을 허용합니다.",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "allow-flight",
		Type:        TypeBool,
		LabelKR:     "비행 허용 (Kick 방지)",
		Description: "서바이벌 모드에서 모드 사용 또는 심한 지연으로 비행 시 킥 처리 여부입니다. (true 권장)",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "spawn-monsters",
		Type:        TypeBool,
		LabelKR:     "몬스터 자연 스폰",
		Description: "밤과 어두운 곳에서 적대적 몬스터가 스폰되도록 허용합니다.",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "spawn-animals",
		Type:        TypeBool,
		LabelKR:     "동물 자연 스폰",
		Description: "소, 돼지, 양 등 우호적 동물의 자연 스폰을 허용합니다.",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "spawn-npcs",
		Type:        TypeBool,
		LabelKR:     "주민 (NPC) 스폰",
		Description: "마을 주민의 스폰 및 생성을 허용합니다.",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "spawn-protection",
		Type:        TypeNumber,
		LabelKR:     "스폰 보호 구역 반경 (블록)",
		Description: "세계 스폰 지점을 중심으로 일반 유저의 블록 수정이 금지되는 반경입니다. (0은 보호 해제)",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "player-idle-timeout",
		Type:        TypeNumber,
		LabelKR:     "잠수 (AFK) 자동 킥 대기 시간 (분)",
		Description: "플레이어가 조작 없이 가만히 있을 때 자동 퇴장시키는 시간(분)입니다. (0은 비활성화)",
		Category:    "게임플레이",
	},
	{
		Source:      "properties",
		Key:         "pause-when-empty-seconds",
		Type:        TypeNumber,
		LabelKR:     "서버 공실 시 일시정지 (초)",
		Description: "접속자가 0명일 때 서버 틱 연산을 일시정지하여 CPU 리소스를 절약합니다. (-1은 항시 실행)",
		Category:    "게임플레이",
	},

	// [월드 & 생성 설정]
	{
		Source:      "properties",
		Key:         "level-name",
		Type:        TypeString,
		LabelKR:     "월드 디렉터리 이름",
		Description: "서버가 로드할 월드 폴더 이름입니다. (기본: world)",
		Category:    "월드 생성",
	},
	{
		Source:      "properties",
		Key:         "level-seed",
		Type:        TypeString,
		LabelKR:     "월드 생성 시드 (Seed)",
		Description: "새 월드 생성 시 사용할 시드 번호 또는 문자열입니다.",
		Category:    "월드 생성",
	},
	{
		Source:      "properties",
		Key:         "level-type",
		Type:        TypeSelect,
		LabelKR:     "월드 지형 유형",
		Description: "월드의 지형 생성 방식입니다.",
		Category:    "월드 생성",
		Options:     []string{"minecraft:normal", "minecraft:flat", "minecraft:large_biomes", "minecraft:amplified"},
	},
	{
		Source:      "properties",
		Key:         "generate-structures",
		Type:        TypeBool,
		LabelKR:     "구조물 생성",
		Description: "마을, 던전, 사원, 네더 요새 등 구조물의 자연 생성을 허용합니다.",
		Category:    "월드 생성",
	},
	{
		Source:      "properties",
		Key:         "generator-settings",
		Type:        TypeString,
		LabelKR:     "커스텀 월드 생성 JSON",
		Description: "커스텀 월드 생성을 위한 세부 JSON 옵션 문자열입니다.",
		Category:    "월드 생성",
	},
	{
		Source:      "properties",
		Key:         "max-world-size",
		Type:        TypeNumber,
		LabelKR:     "최대 월드 경계 반경 (블록)",
		Description: "세계 중심으로부터 이동 가능한 최대 월드 보더(World Border) 반경입니다. (기본: 29999984)",
		Category:    "월드 생성",
	},

	// [성능 및 렌더링]
	{
		Source:      "properties",
		Key:         "view-distance",
		Type:        TypeNumber,
		LabelKR:     "시야 거리 (청크)",
		Description: "서버가 플레이어 클라이언트로 전송하는 시야 청크 반경입니다. (권장: 8~12)",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "simulation-distance",
		Type:        TypeNumber,
		LabelKR:     "연산 거리 (청크)",
		Description: "몹 AI 및 블록 틱 업데이트가 실제로 일어나는 연산 청크 반경입니다. (권장: 6~10)",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "entity-broadcast-range-percentage",
		Type:        TypeNumber,
		LabelKR:     "엔티티 전송 거리 비율 (%)",
		Description: "플레이어에게 엔티티를 패킷으로 렌더링 전송하는 거리 비율입니다. (기본: 100)",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "network-compression-threshold",
		Type:        TypeNumber,
		LabelKR:     "패킷 압축 임계값 (바이트)",
		Description: "네트워크 패킷을 압축하기 시작하는 바이트 크기입니다. (기본: 256, -1은 압축 끄기)",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "max-tick-time",
		Type:        TypeNumber,
		LabelKR:     "최대 단일 틱 허용 시간 (ms)",
		Description: "단일 틱 연산이 이 시간을 초과하면 서버가 멈춘 것으로 판단하고 프로세스를 종료합니다. (-1은 비활성화)",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "sync-chunk-writes",
		Type:        TypeBool,
		LabelKR:     "동기식 청크 디스크 쓰기",
		Description: "청크 데이터를 디스크에 동기식으로 기록하여 비정상 종료 시 롤백을 방지합니다.",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "use-native-transport",
		Type:        TypeBool,
		LabelKR:     "네이티브 소켓 최적화 (epoll/kqueue)",
		Description: "운영체제 커널의 네이티브 네트워크 소켓(epoll, kqueue 등)을 사용하여 통신을 최적화합니다.",
		Category:    "성능 및 렌더링",
	},
	{
		Source:      "properties",
		Key:         "region-file-compression",
		Type:        TypeSelect,
		LabelKR:     "리전 파일 압축 방식",
		Description: "월드 청크 파일(.mca) 압축 알고리즘입니다. (기본: deflate)",
		Category:    "성능 및 렌더링",
		Options:     []string{"deflate", "lz4", "none"},
	},
	{
		Source:      "properties",
		Key:         "max-chained-neighbor-updates",
		Type:        TypeNumber,
		LabelKR:     "블록 연쇄 업데이트 최대 제한",
		Description: "레드스톤 또는 블록 상태의 연쇄 업데이트 수를 제한하여 악의적인 랙 머신을 방지합니다.",
		Category:    "성능 및 렌더링",
	},

	// [보안, 접속 및 인증]
	{
		Source:      "properties",
		Key:         "online-mode",
		Type:        TypeBool,
		LabelKR:     "정품 계정 인증 (Online Mode)",
		Description: "모장/MS 공식 계정 인증을 활성화합니다. (false 시 비공식 계정 접속 허용)",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "enforce-secure-profile",
		Type:        TypeBool,
		LabelKR:     "채팅 보안 프로필 강제 (Mojang 채팅 신고)",
		Description: "Mojang 공식 채팅 서명을 강제합니다. No Chat Reports 모드 충돌 및 경고 창을 없애려면 false로 설정하십시오.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "white-list",
		Type:        TypeBool,
		LabelKR:     "화이트리스트 활성화",
		Description: "화이트리스트 명단에 등록된 플레이어만 서버에 접속할 수 있도록 강제합니다.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "enforce-whitelist",
		Type:        TypeBool,
		LabelKR:     "화이트리스트 즉시 강제 (퇴장)",
		Description: "화이트리스트 명단이 변경되었을 때 접속 중인 제외 대상 플레이어를 즉시 강제 퇴장(Kick)시킵니다.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "hide-online-players",
		Type:        TypeBool,
		LabelKR:     "온라인 플레이어 명단 숨김",
		Description: "서버 목록 핑 조회 시 접속 중인 플레이어 닉네임 목록을 비공개합니다.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "prevent-proxy-connections",
		Type:        TypeBool,
		LabelKR:     "VPN 및 프록시 우회 접속 차단",
		Description: "모장 인증 서버를 통해 VPN 및 프록시 서버를 경유한 접속을 차단합니다.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "log-ips",
		Type:        TypeBool,
		LabelKR:     "콘솔 IP 주소 기록",
		Description: "플레이어 접속 시 콘솔 로그에 IP 주소를 출력합니다.",
		Category:    "보안 및 접속",
	},
	{
		Source:      "properties",
		Key:         "op-permission-level",
		Type:        TypeSelect,
		LabelKR:     "기본 OP 권한 레벨",
		Description: "관리자(OP)에게 부여되는 기본 권한 등급입니다. (4: 서버 종료 포함 전체 권한)",
		Category:    "보안 및 접속",
		Options:     []string{"1", "2", "3", "4"},
	},
	{
		Source:      "properties",
		Key:         "function-permission-level",
		Type:        TypeSelect,
		LabelKR:     "데이터팩 함수 권한 레벨",
		Description: "데이터팩 내 커맨드 함수(/function)가 실행되는 권한 레벨입니다.",
		Category:    "보안 및 접속",
		Options:     []string{"1", "2", "3", "4"},
	},
	{
		Source:      "properties",
		Key:         "rate-limit",
		Type:        TypeNumber,
		LabelKR:     "패킷 전송 속도 제한 (Rate Limit)",
		Description: "단일 플레이어가 초당 전송할 수 있는 최대 패킷 수입니다. (0은 무제한)",
		Category:    "보안 및 접속",
	},

	// [채팅, 네트워크 및 프로토콜]
	{
		Source:      "properties",
		Key:         "chat-spam-threshold-seconds",
		Type:        TypeNumber,
		LabelKR:     "채팅 도배 방지 임계 시간 (초)",
		Description: "채팅 도배를 감지하는 임계 시간(초)입니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "command-spam-threshold-seconds",
		Type:        TypeNumber,
		LabelKR:     "명령어 도배 방지 임계 시간 (초)",
		Description: "명령어 연속 전송 도배를 감지하는 임계 시간(초)입니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "accepts-transfers",
		Type:        TypeBool,
		LabelKR:     "서버 간 플레이어 전송(Transfer) 허용",
		Description: "마인크래프트 1.20.5+ 전송 패킷을 통해 다른 서버로의 이동을 허용합니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "enable-status",
		Type:        TypeBool,
		LabelKR:     "서버 상태(Status Ping) 활성화",
		Description: "서버 목록 화면에서 온라인 여부와 플레이어 수 핑 응답을 제공합니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "enable-query",
		Type:        TypeBool,
		LabelKR:     "GameSpy4 쿼리 프로토콜 활성화",
		Description: "외부 모니터링 툴을 위한 GameSpy4 UDP 쿼리를 활성화합니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "query.port",
		Type:        TypeNumber,
		LabelKR:     "GameSpy4 쿼리 포트",
		Description: "GameSpy4 쿼리 수신 UDP 포트입니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "enable-rcon",
		Type:        TypeBool,
		LabelKR:     "RCON 원격 제어 활성화",
		Description: "웹 매니저 및 원격 툴과의 통신을 위한 마인크래프트 RCON을 활성화합니다. (필수: true)",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "rcon.port",
		Type:        TypeNumber,
		LabelKR:     "RCON 포트",
		Description: "RCON 통신 전용 포트입니다. (기본: 25575)",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "rcon.password",
		Type:        TypeString,
		LabelKR:     "RCON 비밀번호",
		Description: "RCON 접속 인증 비밀번호입니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "broadcast-console-to-ops",
		Type:        TypeBool,
		LabelKR:     "콘솔 명령 OP 브로드캐스트",
		Description: "서버 콘솔에서 실행된 명령어 로그를 접속 중인 관리자(OP)들에게 인게임 채팅으로 출력합니다.",
		Category:    "네트워크 및 통신",
	},
	{
		Source:      "properties",
		Key:         "broadcast-rcon-to-ops",
		Type:        TypeBool,
		LabelKR:     "RCON 실행 결과 OP 브로드캐스트",
		Description: "웹 매니저나 RCON으로 실행된 명령어 출력을 접속 중인 관리자(OP)들에게 전달합니다.",
		Category:    "네트워크 및 통신",
	},

	// [리소스팩 및 기타]
	{
		Source:      "properties",
		Key:         "require-resource-pack",
		Type:        TypeBool,
		LabelKR:     "리소스팩 필수 적용 (강제)",
		Description: "서버 전용 리소스팩 다운로드를 거부한 플레이어를 강제 퇴장(Kick)시킵니다.",
		Category:    "리소스팩 및 데이터팩",
	},
	{
		Source:      "properties",
		Key:         "resource-pack",
		Type:        TypeString,
		LabelKR:     "서버 리소스팩 다운로드 URL",
		Description: "접속 시 자동으로 배포할 리소스팩 ZIP 파일의 직접 다운로드 링크(HTTP/HTTPS)입니다.",
		Category:    "리소스팩 및 데이터팩",
	},
	{
		Source:      "properties",
		Key:         "resource-pack-prompt",
		Type:        TypeString,
		LabelKR:     "리소스팩 설치 확인 안내 문구",
		Description: "플레이어가 리소스팩 수락 여부를 선택할 때 표시되는 맞춤형 안내문입니다.",
		Category:    "리소스팩 및 데이터팩",
	},
	{
		Source:      "properties",
		Key:         "resource-pack-sha1",
		Type:        TypeString,
		LabelKR:     "리소스팩 SHA-1 검증 해시",
		Description: "리소스팩 무결성을 검증하기 위한 40자리 16진수 SHA-1 체크섬입니다.",
		Category:    "리소스팩 및 데이터팩",
	},
	{
		Source:      "properties",
		Key:         "initial-enabled-packs",
		Type:        TypeString,
		LabelKR:     "초기 활성화 데이터팩",
		Description: "새 월드 생성 시 기본으로 활성화할 데이터팩 목록 (기본: vanilla)",
		Category:    "리소스팩 및 데이터팩",
	},
	{
		Source:      "properties",
		Key:         "initial-disabled-packs",
		Type:        TypeString,
		LabelKR:     "초기 비활성화 데이터팩",
		Description: "새 월드 생성 시 기본으로 제외할 데이터팩 목록",
		Category:    "리소스팩 및 데이터팩",
	},

	// ==========================================
	// 2. purpur.yml 핵심 및 특화 설정 (Purpur Specific Settings)
	// ==========================================
	// [Purpur 편의 기능 & 메커니즘]
	{
		Source:      "purpur",
		Key:         "settings.network.kick-for-out-of-order-chat",
		Type:        TypeBool,
		LabelKR:     "비서명/순서 불일치 채팅 킥 방지",
		Description: "클라이언트 지연이나 비서명 채팅 시 채팅 순서 불일치로 인한 강제 퇴장(Kick)을 방지합니다. (false 시 킥 해제)",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "settings.network.upnp-port-forwarding",
		Type:        TypeBool,
		LabelKR:     "UPnP 포트포워딩 자동 구성",
		Description: "공유기 환경에서 UPnP를 통해 마인크래프트 포트포워딩을 자동으로 시도합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "settings.tps-catchup",
		Type:        TypeBool,
		LabelKR:     "틱 지연 자동 만회 (TPS Catchup)",
		Description: "서버에 순간적인 렉이 발생했을 때 틱 속도를 가속하여 밀린 틱을 따라잡습니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "settings.use-alternate-keepalive",
		Type:        TypeBool,
		LabelKR:     "대체 Keepalive 핑 방식",
		Description: "불안정한 네트워크 환경에서 핑 타임아웃 킥을 완화하는 대체 Keepalive 알고리즘을 사용합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "settings.player-deaths-always-show-item",
		Type:        TypeBool,
		LabelKR:     "사망 메시지에 사용 무기/아이템 항상 표시",
		Description: "플레이어가 사망했을 때 사용된 무기나 도구의 이름을 사망 메시지에 항상 노출합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.milk-cures-bad-omen",
		Type:        TypeBool,
		LabelKR:     "우유로 흉조 해제",
		Description: "우유를 마시면 레이드 유발 상태이상(흉조 / Bad Omen)이 치료되도록 허용합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.entity-flames-on-water",
		Type:        TypeBool,
		LabelKR:     "물속 불꽃 즉시 끄기",
		Description: "불붙은 몹이나 플레이어가 물에 닿으면 즉시 화염이 진화되도록 합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.infinite-water-sources",
		Type:        TypeBool,
		LabelKR:     "무한 물 생성 유지",
		Description: "물 블록이 모여 무한 수원을 형성하는 기본 마인크래프트 물리 법칙을 유지합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.lava-infinite-fluid-sources",
		Type:        TypeBool,
		LabelKR:     "용암 무한 수원 생성 허용",
		Description: "물처럼 용암도 3개 블록이 모이면 무한 용암 수원을 형성하도록 허용합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.disable-drops-on-cramming-death",
		Type:        TypeBool,
		LabelKR:     "압사(Cramming) 시 아이템 드롭 방지",
		Description: "한 블록에 몹이 과다하게 뭉쳐 질식사할 때 아이템 드롭을 막아 엔티티 랙을 방지합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.player.totem-of-undying-works-in-inventory",
		Type:        TypeBool,
		LabelKR:     "불사의 토템 인벤토리 발동",
		Description: "손에 들지 않고 인벤토리에만 소지하고 있어도 불사의 토템이 사망 시 자동 발동합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.player.teleport-if-outside-border",
		Type:        TypeBool,
		LabelKR:     "월드 보더 외곽 시 자동 귀환",
		Description: "플레이어가 월드 보더 바깥으로 나가면 안전한 보더 안쪽으로 즉시 텔레포트시킵니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.player.teleport-on-nether-ceiling-damage",
		Type:        TypeBool,
		LabelKR:     "네더 천장 위 데미지 시 지상 귀환",
		Description: "네더 천장 위(Y=128+)에서 지속 데미지를 입으면 안전한 네더 지상으로 텔레포트합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.player.allow-headless-pistons",
		Type:        TypeBool,
		LabelKR:     "헤드리스 피스톤 버그 허용",
		Description: "기반암 파괴 기술에 사용되는 헤드리스 피스톤 글리치를 서버에서 허용합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "gameplay-mechanics.player.creative-one-punch",
		Type:        TypeBool,
		LabelKR:     "크리에이티브 모드 몹 한 방 처치",
		Description: "크리에이티브 모드 플레이어가 모든 몹을 단 한 번의 타격으로 처치할 수 있게 합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "tools.hoe.replant-crops",
		Type:        TypeBool,
		LabelKR:     "괭이로 수확 시 작물 자동 재심기",
		Description: "다 자란 작물을 괭이로 우클릭/타격 수확 시 자동으로 씨앗을 즉시 다시 심습니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "tools.hoe.replant-nether-warts",
		Type:        TypeBool,
		LabelKR:     "괭이로 네더 와트 자동 재심기",
		Description: "괭이로 네더 와트를 수확할 때 즉시 영혼 모래 위에 다시 심습니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "blocks.anvil.allow-colors",
		Type:        TypeBool,
		LabelKR:     "모루에서 색상 코드(&) 이름 변경 허용",
		Description: "모루에서 아이템 이름을 변경할 때 '&c', '&6' 등의 색상 포맷 코드를 지원합니다.",
		Category:    "Purpur 편의 기능",
	},

	// [Purpur 몹 라이딩 & 엔티티 조작]
	{
		Source:      "purpur",
		Key:         "ridable-settings.babies-are-ridable",
		Type:        TypeBool,
		LabelKR:     "새끼 몹 탑승 가능",
		Description: "성체가 아닌 새끼 몹에게도 우클릭하여 올라탈 수 있도록 허용합니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "ridable-settings.untamed-tamables-are-ridable",
		Type:        TypeBool,
		LabelKR:     "길들이지 않은 몹 탑승 허용",
		Description: "길들이기 전 상태의 야생 몹에도 우클릭하여 탑승할 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "ridable-settings.use-night-vision",
		Type:        TypeBool,
		LabelKR:     "몹 탑승 시 야간 투시 효과",
		Description: "탑승 가능한 몹에 올라타면 플레이어에게 야간 투시 버프를 부여합니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.creeper.ridable",
		Type:        TypeBool,
		LabelKR:     "크리퍼 탑승 가능",
		Description: "플레이어가 크리퍼 위에 우클릭하여 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.iron_golem.ridable",
		Type:        TypeBool,
		LabelKR:     "철 골렘 탑승 가능",
		Description: "플레이어가 거대한 철 골렘 위에 우클릭하여 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.phantom.ridable",
		Type:        TypeBool,
		LabelKR:     "팬텀 비행 탑승 가능",
		Description: "플레이어가 하늘을 나는 팬텀에 탑승하여 비행 조종할 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.phantom.spawn-only-above-sea-level",
		Type:        TypeBool,
		LabelKR:     "팬텀 해수면 이상 스폰",
		Description: "팬텀이 Y=63(해수면) 위에서만 스폰되도록 제한하여 지하 괴롭힘을 방지합니다.",
		Category:    "Purpur 편의 기능",
	},
	{
		Source:      "purpur",
		Key:         "mobs.villager.ridable",
		Type:        TypeBool,
		LabelKR:     "주민 탑승 가능",
		Description: "플레이어가 마을 주민에게 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.enderman.ridable",
		Type:        TypeBool,
		LabelKR:     "엔더맨 탑승 가능",
		Description: "플레이어가 엔더맨 위에 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.dolphin.ridable",
		Type:        TypeBool,
		LabelKR:     "돌고래 수중 탑승 가능",
		Description: "수영 중 돌고래에 올라타 고속으로 헤엄칠 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.warden.ridable",
		Type:        TypeBool,
		LabelKR:     "워든 탑승 가능",
		Description: "강력한 워든 위에 올라타서 이동할 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.sniffer.ridable",
		Type:        TypeBool,
		LabelKR:     "스니퍼 탑승 가능",
		Description: "고대 생물 스니퍼 위에 우클릭하여 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.zombie.ridable",
		Type:        TypeBool,
		LabelKR:     "좀비 탑승 가능",
		Description: "좀비에게 우클릭하여 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.skeleton.ridable",
		Type:        TypeBool,
		LabelKR:     "스켈레톤 탑승 가능",
		Description: "스켈레톤에게 우클릭하여 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.spider.ridable",
		Type:        TypeBool,
		LabelKR:     "거미 벽타기 탑승 가능",
		Description: "거미에 올라타 벽을 오르며 이동할 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.wolf.ridable",
		Type:        TypeBool,
		LabelKR:     "늑대 탑승 가능",
		Description: "늑대에게 올라타 함께 달릴 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
	{
		Source:      "purpur",
		Key:         "mobs.cat.ridable",
		Type:        TypeBool,
		LabelKR:     "고양이 탑승 가능",
		Description: "고양이에게 올라탈 수 있습니다.",
		Category:    "Purpur 몹 라이딩",
	},
}

// StandardDefaults provides sensible standard default values for Minecraft & Purpur settings.
var StandardDefaults = map[string]string{
	"difficulty":                         "normal",
	"gamemode":                           "survival",
	"force-gamemode":                     "false",
	"hardcore":                           "false",
	"motd":                               "A Minecraft Server for Friends",
	"server-name":                        "Unknown Server",
	"server-port":                        "25565",
	"server-ip":                          "",
	"max-players":                        "20",
	"pvp":                                "true",
	"allow-flight":                       "false",
	"spawn-monsters":                     "true",
	"spawn-animals":                      "true",
	"spawn-npcs":                         "true",
	"spawn-protection":                   "16",
	"player-idle-timeout":                "0",
	"pause-when-empty-seconds":           "-1",
	"level-name":                         "world",
	"level-seed":                         "",
	"level-type":                         "minecraft:normal",
	"generate-structures":                "true",
	"generator-settings":                 "{}",
	"max-world-size":                     "29999984",
	"view-distance":                      "10",
	"simulation-distance":                "10",
	"entity-broadcast-range-percentage":  "100",
	"network-compression-threshold":      "256",
	"max-tick-time":                      "60000",
	"sync-chunk-writes":                  "true",
	"use-native-transport":               "true",
	"region-file-compression":            "deflate",
	"max-chained-neighbor-updates":       "1000000",
	"online-mode":                        "true",
	"enforce-secure-profile":             "false",
	"white-list":                         "false",
	"enforce-whitelist":                  "false",
	"hide-online-players":                "false",
	"prevent-proxy-connections":          "false",
	"log-ips":                            "true",
	"op-permission-level":                "4",
	"function-permission-level":          "2",
	"rate-limit":                         "0",
	"chat-spam-threshold-seconds":        "10",
	"command-spam-threshold-seconds":     "10",
	"accepts-transfers":                  "false",
	"enable-status":                      "true",
	"enable-query":                       "false",
	"query.port":                         "25565",
	"enable-rcon":                        "true",
	"rcon.port":                          "25575",
	"rcon.password":                      "rcon_password",
	"broadcast-console-to-ops":           "true",
	"broadcast-rcon-to-ops":              "true",
	"require-resource-pack":              "false",
	"resource-pack":                      "",
	"resource-pack-prompt":               "",
	"resource-pack-sha1":                 "",
	"initial-enabled-packs":              "vanilla",
	"initial-disabled-packs":             "",
	"settings.network.kick-for-out-of-order-chat": "false",
	"settings.network.upnp-port-forwarding":       "false",
	"settings.tps-catchup":                       "true",
	"settings.use-alternate-keepalive":           "false",
	"settings.player-deaths-always-show-item":    "false",
	"gameplay-mechanics.milk-cures-bad-omen":     "true",
	"gameplay-mechanics.entity-flames-on-water":  "true",
	"gameplay-mechanics.infinite-water-sources":  "true",
	"gameplay-mechanics.lava-infinite-fluid-sources": "false",
	"gameplay-mechanics.disable-drops-on-cramming-death": "false",
	"gameplay-mechanics.player.totem-of-undying-works-in-inventory": "false",
	"gameplay-mechanics.player.teleport-if-outside-border": "true",
	"gameplay-mechanics.player.teleport-on-nether-ceiling-damage": "true",
	"gameplay-mechanics.player.allow-headless-pistons": "false",
	"gameplay-mechanics.player.creative-one-punch": "false",
	"tools.hoe.replant-crops":                    "false",
	"tools.hoe.replant-nether-warts":              "false",
	"blocks.anvil.allow-colors":                  "false",
	"ridable-settings.babies-are-ridable":        "true",
	"ridable-settings.untamed-tamables-are-ridable": "true",
	"ridable-settings.use-night-vision":          "false",
	"mobs.creeper.ridable":                       "false",
	"mobs.iron_golem.ridable":                    "false",
	"mobs.phantom.ridable":                       "false",
	"mobs.phantom.spawn-only-above-sea-level":     "true",
	"mobs.villager.ridable":                      "false",
	"mobs.enderman.ridable":                      "false",
	"mobs.dolphin.ridable":                       "false",
	"mobs.warden.ridable":                        "false",
	"mobs.sniffer.ridable":                       "false",
	"mobs.zombie.ridable":                        "false",
	"mobs.skeleton.ridable":                      "false",
	"mobs.spider.ridable":                        "false",
	"mobs.wolf.ridable":                          "false",
	"mobs.cat.ridable":                           "false",
}


